app/models.py
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__='users'

    id=db.Column(db.Integer, primary_key=True)
    username=db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    comments=db.relationship('Comment',backref = 'user',lazy = "dynamic")
    

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Comment(db.Model):
        __tablename__='comments'

        id = db.Column(db.Integer,primary_key = True)
        name=db.Column(db.String(255))
        comment=db.Column(db.String())
        user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio=TextAreaField('Tell us something about you.', validators=[Required()])
    submit=SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, login_manager
from .config import config_options
from flask_bootstrap import Bootstrap
from flask_mail import Mail

db=SQLAlchemy()
login_manager = LoginManager()
bootstrap=Bootstrap()
login_manager_protection = 'strong'
login_manager.login_view = 'auth.login'
mail=Mail()

def create_app(config_name):

    #Initializing application
    app=Flask(__name__)

    # Setting up configuration
    app.config.from_object(config_options[config_name])
    
    from .main import main as main_blueprint
    from .auth import auth

    # Initializing Flask Extensions
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth, url_prefix='/authenticate')

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
   
    return app

app/main/__init__.py
from flask import Blueprint

main=Blueprint('main', __name__)

from . import views 

app/main/views.py
from . import main
from flask import render_template, abort, redirect, url_for
from ..models import User
from .. import db
from .forms import UpdateProfile
from flask_login import login_required


@main.route('/')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/post')
def post():
    return render_template('post.html')

@main.route('/contact')
def contact():
    return render_template('contact.html')

@main.route('/user/uname')
def profife(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/about.html
{% extends 'base.html'%}

<!-- block content  -->
{% block content%}
   <div class="container">
       <img src="{{ url_for('static',filename='img/about-bg.jpg') }}") center no-repeat;} width="1000px">
   </div><br> <br>

   <div class="container">
       <h3>About Us</h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero dolorum veniam, aspernatur voluptate aliquid alias quae nihil ut aliquam sed deleniti dolorem molestias voluptates ad ratione, error neque recusandae velit?</p>
   </div>
{% endblock%}

app/templates/base.html
<!DOCTYPE html>
{% extends 'bootstrap/base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sharry's Blog</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='clean-blog.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <!-- Navbar block  --> 
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}

        {% block content%}
        
        {% endblock%}
</body>
</html>

app/templates/contact.html
{% extends 'base.html'%}

<!-- block content  -->
{% block content%}
   <div class="container">
       <img src="{{ url_for('static',filename='img/contact-bg.jpg') }}") center no-repeat;} width="1000px">
   </div><br> <br>

   <div class="container">
       <h3>How to Contact Us</h3>
       <p>You can find us on twitter @sharrycherop and on our parent blog:<a href="http://boldandgracious.blogspot.com/" target="_blank">Click Here...</a></p>
       </div>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}

<!-- block content  -->
{% block content%}
   <div class="container">
       <img src="{{ url_for('static',filename='img/home-bg.jpg') }}") center no-repeat;} width="1000px">
   </div><br> <br>

   <div class="container">
       <h3>What is Love?</h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero dolorum veniam, aspernatur voluptate aliquid alias quae nihil ut aliquam sed deleniti dolorem molestias voluptates ad ratione, error neque recusandae velit?</p>
   </div>
   <div class="container">
       <h3>Business Ideas</h3>
       <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi exercitationem architecto aperiam voluptas illo saepe vel placeat perferendis consequatur, et cumque consectetur tenetur fugit quod. Nobis fugit iste unde quae!</p>
   </div>
{% endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Sharry's Blog </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/about">About</a></li>
                <li><a href="/post">Post</a></li>
                <li><a href="/contact">Contact Us</a></li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
    </div>
</div>

app/templates/post.html
{% extends 'base.html'%}

<!-- block content  -->
{% block content%}
   <div class="container">
       <img src="{{ url_for('static',filename='img/post-bg.jpg') }}") center no-repeat;} width="1000px">
   </div><br> <br>

   
{% endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}